import { Article } from '../types';

const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
  'of', 'with', 'by', 'from', 'is', 'are', 'was', 'were', 'be', 'been',
  'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would',
  'could', 'should', 'may', 'might', 'shall', 'can', 'need', 'it', 'its',
  'this', 'that', 'these', 'those', 'you', 'he', 'she', 'we', 'they',
  'what', 'which', 'who', 'whom', 'whose', 'where', 'when', 'why', 'how',
  'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other', 'some',
  'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too',
  'very', 'just', 'about', 'above', 'after', 'again', 'against', 'before',
  'between', 'during', 'into', 'through', 'while', 'out', 'up', 'down',
  'off', 'over', 'under', 'as', 'if', 'then', 'once', 'here', 'there',
  'also', 'new', 'one', 'two', 'first', 'last', 'back', 'still', 'even',
  'well', 'many', 'us', 'me', 'him', 'her', 'them', 'my', 'your', 'his',
  'our', 'their', 'am', 'like', 'get', 'got', 'make', 'made', 'go',
  'going', 'went', 'come', 'came', 'take', 'took', 'know', 'see', 'think',
  'want', 'give', 'use', 'find', 'tell', 'ask', 'work', 'seem', 'feel',
  'try', 'leave', 'call', 'good', 'great', 'little', 'big', 'long', 'old',
  'right', 'high', 'different', 'small', 'large', 'next', 'early', 'young',
  'important', 'public', 'bad', 'said', 'say', 'says', 'told', 'let',
  'put', 'keep', 'hold', 'help', 'turn', 'start', 'show', 'hear', 'play',
  'run', 'move', 'live', 'believe', 'bring', 'happen', 'write', 'provide',
  'sit', 'stand', 'lose', 'pay', 'meet', 'include', 'continue', 'set',
  'learn', 'change', 'lead', 'understand', 'watch', 'follow', 'stop',
  'create', 'speak', 'read', 'allow', 'add', 'spend', 'grow', 'open',
  'walk', 'win', 'offer', 'remember', 'love', 'consider', 'appear',
  'buy', 'wait', 'serve', 'die', 'send', 'expect', 'build', 'stay',
  'fall', 'cut', 'reach', 'kill', 'remain', 'suggest', 'raise', 'pass',
  'sell', 'require', 'report', 'decide', 'pull', 'develop', 'thank',
  'become', 'begin', 'look', 'want', 'going', 'going', 'around', 'away',
  'according', 'across', 'actually', 'already', 'always', 'another',
  'anything', 'behind', 'below', 'beside', 'however', 'including',
  'instead', 'itself', 'least', 'less', 'maybe', 'minus', 'moreover',
  'mostly', 'myself', 'near', 'nearly', 'neither', 'never', 'nobody',
  'none', 'nonetheless', 'normally', 'nothing', 'now', 'nowhere',
  'obviously', 'often', 'onto', 'others', 'otherwise', 'outside',
  'overall', 'perhaps', 'please', 'plus', 'possible', 'presumably',
  'probably', 'provided', 'quite', 'rather', 'really', 'regarding',
  'relatively', 'respectively', 'round', 'several', 'she', 'simply',
  'since', 'somehow', 'someone', 'something', 'sometime', 'sometimes',
  'somewhat', 'somewhere', 'specifically', 'therefore', 'together',
  'toward', 'towards', 'unless', 'unlike', 'unlikely', 'until', 'upon',
  'various', 'via', 'whether', 'whole', 'within', 'without', 'yet',
  'yours', 'yourself', 'yourselves', 'etc', 'per', 'vs', 'aka',
  'canada', 'canadian', 'ontario', 'quebec', 'toronto', 'vancouver',
  'montreal', 'ottawa', 'calgary', 'edmonton', 'winnipeg', 'halifax',
  'st', 'mr', 'mrs', 'ms', 'dr', 'prof', 'jr', 'sr', 'inc', 'ltd',
  'corp', 'co', 'gov', 'monday', 'tuesday', 'wednesday', 'thursday',
  'friday', 'saturday', 'sunday', 'january', 'february', 'march',
  'april', 'june', 'july', 'august', 'september', 'october', 'november',
  'december', 'today', 'yesterday', 'tomorrow', 'morning', 'afternoon',
  'evening', 'night', 'week', 'month', 'year', 'years', 'day', 'days',
  'time', 'way', 'thing', 'things', 'people', 'man', 'men', 'woman',
  'women', 'hour', 'minute', 'second', 'north', 'south', 'east', 'west',
  'central', 'northern', 'southern', 'eastern', 'western',
  'says', 'announced', 'confirmed', 'revealed', 'statement', 'official',
  'officials', 'minister', 'premier', 'prime', 'president', 'leader',
  'party', 'parties', 'election', 'vote', 'voters', 'campaign', 'law',
  'laws', 'bill', 'bills', 'policy', 'policies', 'plan', 'plans',
  'program', 'programs', 'budget', 'tax', 'taxes', 'spending', 'cut',
  'cuts', 'increase', 'increases', 'rise', 'fall', 'drop', 'change',
  'changes', 'issue', 'issues', 'problem', 'problems', 'crisis',
  'situation', 'case', 'cases', 'event', 'events', 'incident',
  'attack', 'attacks', 'death', 'deaths', 'killed', 'died', 'injured',
  'injuries', 'victim', 'victims', 'suspect', 'suspects', 'arrested',
  'arrest', 'charges', 'charged', 'trial', 'guilty', 'crime', 'crimes',
  'criminal', 'investigation', 'police', 'officer', 'officers',
  'department', 'agency', 'agencies', 'service', 'services', 'health',
  'care', 'hospital', 'hospitals', 'doctor', 'doctors', 'patient',
  'patients', 'treatment', 'medical', 'virus', 'pandemic', 'vaccine',
  'vaccines', 'covid', 'school', 'schools', 'student', 'students',
  'teacher', 'teachers', 'education', 'university', 'college', 'class',
  'classes', 'study', 'studies', 'research', 'business', 'company',
  'companies', 'market', 'markets', 'stock', 'stocks', 'price', 'prices',
  'cost', 'costs', 'money', 'dollar', 'dollars', 'billion', 'million',
  'thousand', 'hundred', 'economic', 'economy', 'trade', 'deal', 'deals',
  'agreement', 'agreements', 'industry', 'industries', 'sector',
  'sectors', 'oil', 'gas', 'energy', 'water', 'food', 'housing', 'home',
  'homes', 'house', 'houses', 'property', 'real', 'estate', 'rent',
  'job', 'jobs', 'worker', 'workers', 'employment', 'unemployment',
  'wage', 'wages', 'union', 'unions', 'strike', 'strikes', 'weather',
  'storm', 'storms', 'snow', 'rain', 'wind', 'flood', 'floods', 'fire',
  'fires', 'wildfire', 'wildfires', 'temperature', 'heat', 'cold',
  'winter', 'spring', 'summer', 'climate', 'environment', 'pollution',
  'emissions', 'carbon', 'sport', 'sports', 'game', 'games', 'team',
  'teams', 'player', 'players', 'coach', 'season', 'win', 'wins',
  'loss', 'losses', 'hockey', 'football', 'basketball', 'soccer',
  'tennis', 'golf', 'race', 'races', 'championship', 'cup', 'medal',
  'medals', 'tech', 'technology', 'computer', 'computers', 'software',
  'hardware', 'internet', 'online', 'digital', 'data', 'information',
  'phone', 'phones', 'mobile', 'app', 'apps', 'website', 'social',
  'media', 'facebook', 'twitter', 'instagram', 'tiktok', 'youtube',
  'google', 'apple', 'microsoft', 'amazon', 'robot', 'robots', 'machine',
  'learning', 'cyber', 'security', 'hack', 'hacking', 'privacy', 'war',
  'wars', 'military', 'army', 'navy', 'air', 'force', 'defense',
  'defence', 'troops', 'soldier', 'soldiers', 'weapon', 'weapons',
  'nuclear', 'missile', 'missiles', 'peace', 'treaty', 'treaties',
  'conflict', 'conflicts', 'fight', 'fighting', 'battle', 'battles',
  'invasion', 'sanctions', 'russia', 'russian', 'ukraine', 'ukrainian',
  'china', 'chinese', 'united', 'states', 'america', 'american',
  'british', 'europe', 'european', 'middle', 'israel', 'israeli',
  'iran', 'iranian', 'india', 'indian', 'japan', 'japanese', 'korea',
  'korean', 'australia', 'australian', 'brazil', 'brazilian', 'mexico',
  'mexican', 'africa', 'african', 'asia', 'asian', 'council',
  'parliament', 'senate', 'senator', 'senators', 'mp', 'mps',
  'committee', 'committees', 'debate', 'debates', 'decision',
  'decisions', 'approval', 'approved', 'rejected', 'passed',
  'legislation', 'regulation', 'regulations', 'rule', 'rules', 'order',
  'orders', 'ban', 'banned', 'bans', 'fine', 'fines', 'penalty',
  'penalties', 'warning', 'warnings', 'emergency', 'emergencies',
  'disaster', 'disasters', 'accident', 'accidents', 'crash', 'crashes',
  'train', 'trains', 'bus', 'buses', 'car', 'cars', 'truck', 'trucks',
  'road', 'roads', 'highway', 'highways', 'bridge', 'bridges', 'transit',
  'transport', 'transportation', 'airport', 'airports', 'flight',
  'flights', 'airline', 'airlines', 'travel', 'border', 'borders',
  'immigration', 'immigrant', 'immigrants', 'refugee', 'refugees',
  'asylum', 'citizen', 'citizens', 'citizenship', 'passport', 'visas',
  'visa', 'community', 'communities', 'residents', 'resident',
  'population', 'census', 'survey', 'surveys', 'poll', 'polls',
  'opinion', 'opinions', 'support', 'oppose', 'opposition', 'protest',
  'protests', 'protester', 'protesters', 'demonstration', 'march',
  'marches', 'rally', 'rallies', 'activist', 'activists', 'movement',
  'movements', 'organization', 'organizations', 'group', 'groups',
  'association', 'charity', 'charities', 'volunteer', 'volunteers',
  'fund', 'funds', 'fundraising', 'donation', 'donations', 'donate',
  'gift', 'gifts', 'award', 'awards', 'prize', 'prizes', 'recognition',
  'celebration', 'festival', 'festivals', 'concert', 'concerts', 'show',
  'shows', 'movie', 'movies', 'film', 'films', 'actor', 'actors',
  'actress', 'actresses', 'director', 'directors', 'music', 'song',
  'songs', 'singer', 'singers', 'band', 'bands', 'album', 'albums',
  'artist', 'artists', 'art', 'exhibition', 'gallery', 'galleries',
  'museum', 'museums', 'library', 'libraries', 'book', 'books', 'author',
  'authors', 'writer', 'writers', 'writing', 'news', 'story', 'stories',
  'article', 'articles', 'report', 'reports', 'coverage', 'update',
  'updates', 'breaking', 'developing', 'latest', 'recent', 'current',
  'top', 'main', 'major', 'key', 'primary', 'leading', 'chief', 'senior',
  'junior', 'former', 'following', 'among', 'along', 'around', 'near',
  'far', 'away', 'close', 'open', 'closed', 'full', 'empty', 'half',
  'part', 'parts', 'piece', 'pieces', 'side', 'sides', 'point', 'points',
  'line', 'lines', 'area', 'areas', 'space', 'place', 'places', 'room',
  'building', 'buildings', 'construction', 'development', 'developments',
  'project', 'projects', 'site', 'sites', 'land', 'ground', 'field',
  'fields', 'park', 'parks', 'garden', 'gardens', 'forest', 'forests',
  'tree', 'trees', 'river', 'rivers', 'lake', 'lakes', 'ocean', 'sea',
  'mountain', 'mountains', 'hill', 'hills', 'island', 'islands', 'beach',
  'beaches', 'coast', 'shore', 'port', 'harbour', 'bay', 'gulf',
  'channel', 'canal', 'dam', 'tunnel', 'tower', 'church', 'churches',
  'temple', 'monument', 'monuments', 'memorial', 'memorials', 'statue',
  'statues', 'plaza', 'square', 'street', 'streets', 'avenue', 'lane',
  'drive', 'court', 'crescent', 'freeway', 'expressway', 'intersection',
  'junction', 'corner', 'block', 'district', 'zone', 'suburb', 'suburbs',
  'downtown', 'centre', 'center', 'upper', 'lower', 'inner', 'outer',
  'left', 'front', 'top', 'bottom', 'middle', 'inside', 'outside',
  'beneath', 'beyond', 'ahead', 'forward', 'straight', 'direct',
  'immediate', 'sudden', 'gradual', 'rapid', 'slow', 'quick', 'fast',
  'steady', 'constant', 'continuous', 'occasional', 'rare', 'common',
  'usual', 'normal', 'typical', 'standard', 'regular', 'special',
  'unique', 'particular', 'specific', 'general', 'total', 'entire',
  'complete', 'partial', 'finished', 'ready', 'able', 'capable',
  'likely', 'certain', 'sure', 'clear', 'obvious', 'visible', 'hidden',
  'secret', 'private', 'personal', 'professional', 'formal', 'informal',
  'legal', 'illegal', 'valid', 'invalid', 'true', 'false', 'real',
  'fake', 'original', 'similar', 'same', 'equal', 'related', 'connected',
  'together', 'apart', 'alone', 'single', 'double', 'multiple',
  'numerous', 'any', 'everyone', 'everything', 'everywhere', 'finally',
  'further', 'generally', 'greatly', 'highly', 'increasingly', 'largely',
  'lately', 'mainly', 'merely', 'particularly', 'partly', 'perfectly',
  'possibly', 'previously', 'primarily', 'quickly', 'rarely', 'recently',
  'seriously', 'simply', 'slightly', 'slowly', 'suddenly', 'typically',
  'ultimately', 'usually', 'widely', 'despite', 'except', 'worth',
  'times', 'divided', 'comes', 'amid', 'three', 'facing', 'much', 'city',
  'national', 'members', 'province', 'local', 'used', 'country', 'family',
  'looking', 'governments', 'pressure', 'centres', 'world', 'provincial',
  'federal', 'canadians', 'mark', 'person', 'grizzly', 'government',
  'bear', 'authorities',
]);

export interface KeywordInfo {
  word: string;
  count: number;
}

export function extractKeywords(articles: Article[], maxKeywords: number = 30): KeywordInfo[] {
  const frequency = new Map<string, number>();
  const minFrequency = Math.max(2, Math.floor(articles.length * 0.01));

  for (const article of articles) {
    const text = `${article.title} ${article.description}`.toLowerCase();
    const tokens = text.match(/[a-z]{4,}/g) || [];

    const seen = new Set<string>();
    for (const token of tokens) {
      if (STOP_WORDS.has(token) || seen.has(token)) continue;
      seen.add(token);
      frequency.set(token, (frequency.get(token) || 0) + 1);
    }
  }

  return [...frequency.entries()]
    .filter(([, count]) => count >= minFrequency)
    .map(([word, count]) => ({ word, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, maxKeywords);
}
